### ISSUE TITLE
Permission problem after playername-change

### ISSUE THREAD

**Issue by DasFantatier** [ProjectEssentials/ProjectEssentials-Permissions#24]
### Describe the bug
> I changed my ingame player name in minecraft.net lately and since then i can´t use any commands like /time set day oder /gamemode. I am pretty shure this was the beginning of the problem because it happened right after this. (all other OP´s can use their commands like always)
We play on a 1.15.2 Server with forge 31.1.0 and different mods.
Also with project core, permission, home and cooldown.

I tested it in singleplayer and multiplayer and i had the same problem, just the error messages are different on the screen.
We open Minecraft with twitch, so i tested: deleting all project mods and also the folder of it - and my commands worked again! (singleplayer)
I reinstalled the project mods and the error was again! (Singleplayer)

So it seems it has nothing to do with our server because the problem occurs in singleplayer too, but only with the project mods i mentioned.
Cheats are ON, and withouth the project mods everything is working fine.
I deinstalled them and installed them new, but the issue stays the same.

So I need your help please, I am pretty sure it has something to do with my ingame name change because it happens since then. I am op on server and singleplayer, cheats are on, my op level is 4, so everything should work fine like before - i haven´t changed anything, also not at the project essentials mods or configuration/permissions.
My new ingame name and my uuid are correctly in the files. 

### Screenshots
Error on the Server:
![Screen Shot 04-07-20 at 03 22 PM 002](https://user-images.githubusercontent.com/62701156/78677873-878afc80-78e8-11ea-9d0d-c2cce7dd94ea.PNG)

Error in Singleplayer:
![Screen Shot 04-07-20 at 03 22 PM 001](https://user-images.githubusercontent.com/62701156/78677886-8b1e8380-78e8-11ea-9d2f-5d5bf0e319ae.PNG)

### Environment information
> - Project Essentials Permissions version: [Project Essentials Permissions-1.15.2-1.0.2.jar]
> - Project Essentials Core version: [Project Essentials Core-MOD-1.15.2-1.1.0.jar]
> - Project Essentials Modules version: [Project Essentials Home-1.15.2-1.1.0.jar AND Project Essentials Cooldown-1.15.2-1.0.2.jar]
> - Minecraft / Forge version: [1.15.2 / 31.1.0]

### Additional context
> - As I already mentioned - all the server and singleplayer settings are like before when everything worked fine for me - all other op´s can use their commands like always. The problem occurs only by me (I changed my ingame name lately) and accours only with the project essential mods. If i delete them it is working again.
Maybe there is a project file anywhere which doesn´t get deleted when i deinstall it. Because i tried deinstalling and also deleting the folder in Minecraft i found after it, deinstalled is working, but if i reinstall it again the error occurs again.
I tested different commands like /time, /gamemode, /tp, and so on....

### Log files.

Only message in log file with the error:

SINGLEPLAYER:
[15:22:00] [Server thread/INFO]: Player (Das_Fantatier) failed to executing "/time" command
    - Reason: permission level executing command more than player permission level.
[15:22:00] [Render thread/INFO]: [CHAT] §cYou §7don't have permission §cto execute this command.

SERVER:
[07Apr2020 15:22:27.980] [Server thread/INFO] [com.mairwunnx.projectessentials.core.vanilla.commands.TimeCommand/]: Player (Das_Fantatier) failed to executing "/time" command
    - Reason: permission level executing command more than player permission level.

Thank you in advice and sorry for this long text, I just wanted to be sure to mention everything necessary!

**Comment by MairwunNx** [comment]
Hi again @DasFantatier! Permissions module have a small logic bug *(I know about this bug and do not rush to fix it.)* with checking on operator level. Operators list checks on dedicated \ internal server starting. In single player i don't know what it work. 

Project Essentials data stores on single player game same like on server. For all single player worlds is one configuration. If you want play with permissions module in single player and you want have all permissions you need add all permissions once. 

`/perm user <...> set "*"` or you can set default group "owner" through configuration. Your problem solved.

Operator level also checked when permissions module not exist. You can remove permissions module in single player (*In general, this module is not intended for installation on a single world because it is pointless, but there may be cases when it is necessary.*).

If you have only problem with checking permissions even you have op level 4 - create another issue with name `Operator level checking incorrectly work on client side.`.

**Also i see what you have problem with localization on server, enable server-localization in config/localization.json and change value to true.**

### Continue reply on your issue:

Project Essentials all mods uses nickname as player id because most of minecraft forge servers works with disabled online mode. I can't use uuid, because i don't know what may side effects.

UUID uses in project for storing home data and fly \ god player state.

I can add UUID support to permissions module if you need it.

But currently just add your new nickname to permissions configuration, it's worked?

### Also please drop `permissions.json` as file and attach you mojang nickname and `latest.log`.

**Comment by DasFantatier** [comment]
I changed the value from localization to true now.

**And here is the permissions.json**
https://pastebin.com/p2yvyckj

 **and localization.json:**
{
    "enabled": true,
    "fallbackLanguage": "en_us"
}

I can´t send them because this website doesn´t allow 7zip or rar or json files.

I am very sorry to say, but i don´t know how to put my nickname into the file. Do i have to copy the code with "nickname"? Where now is written "server"? 
![Screen Shot 04-07-20 at 06 08 PM](https://user-images.githubusercontent.com/62701156/78693993-4ef51e00-78fc-11ea-986b-144327f36861.PNG)


I don´t need these mods on my single player, i just tested the issue with it because i didn´t want to change anything on the server yet. So I really only need the solution for server.

**Comment by DasFantatier** [comment]
And here is the latest server-log

[latest.log](https://github.com/ProjectEssentials/ProjectEssentials-Permissions/files/4445819/latest.log)


Oh - I just closed the issue by accident :/

**Comment by MairwunNx** [comment]
`#server` it like an example.

If you need add your name: you need add new object to `users` array. Don't forget put `,` before adding new object.

```json
{
    "nickname": "<your name>"
    // next like in `#server` player.
}
```

Permissions array like `users`.

```json
"permissions": [
]
```

With one permissions:

```
"permissions": [
    "ess.teleport.*"
]
```

With two permissions:

```
"permissions": [
    "ess.teleport.*",
    "ess.blablabla"
]
```


*If you don't know json syntax you need read https://www.digitalocean.com/community/tutorials/an-introduction-to-json*

Full example:

```json
"users": [
    ... ,
    {
        "nickname": "Das_Fantatier",
        "group": "owner",
        "permissions": []
    }
]
```

**Comment by MairwunNx** [comment]
Problem solved? @DasFantatier.

**Comment by DasFantatier** [comment]
So - I haven´t changed anything in the permission files because i haven´t found time to read the manual and everything.

The commands are working again now out from nowhere after days.
Thank´s for the support.

**Comment by MairwunNx** [comment]
Is everything okay? If there are problems that you can’t solve, report them. =).
